this notebook is for testing and trying things out

In [55]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [56]:
db_path = "../../data/cycling_big.db"
riders_csv_path = "../../data/data/rider_infos.csv"
results_path = "../../data/data/results/"
team_urls_path = "../../data/data/team_urls/"

In [57]:
riders = pd.read_csv(riders_csv_path)

In [58]:
conn = sqlite3.connect(db_path)
race = pd.read_sql_query("SELECT * FROM race_results", conn)
conn.close()

In [59]:
riders.head(1)

,Unnamed: 0,fullname,team,birthdate,country,height,weight,rider_url,pps,rdr
0,0,BARDET Romain,Team DSM,1990-11-09,France,1.84,65.0,https://www.procyclingstats.com/rider/romain-b...,"{'One day races': '2620', 'GC': '5138', 'Time ...","{'PCS Ranking': '43', 'UCI World Ranking': '52..."

In [60]:
riders.drop(['Unnamed: 0', 'rider_url'], axis=1, inplace=True)
riders.head(1)

,fullname,team,birthdate,country,height,weight,pps,rdr
0,BARDET Romain,Team DSM,1990-11-09,France,1.84,65.0,"{'One day races': '2620', 'GC': '5138', 'Time ...","{'PCS Ranking': '43', 'UCI World Ranking': '52..."

In [61]:
race.head()

,id,Rnk,GC,Timelag,BiB,Rider,Age,Team,UCI,Pnt,...,Stage_Type,Start,Finish,Race_ID,Stage_Number,Length,Category,Race_url,Stage_url,rider_id
0,1,1,1.0,+0:00,0,GREIPEL André,29,Lotto Belisol Team,6.0,50.0,...,RR,Prospect,Clare,0,1,149 km,ME - Men Elite,race/tour-down-under/2012,/stage-1/result/result,659ed585810c65fe22255a5e4a9b7838
1,2,2,2.0,+0:04,0,PETACCHI Alessandro,38,Lampre - ISD,4.0,30.0,...,RR,Prospect,Clare,0,1,149 km,ME - Men Elite,race/tour-down-under/2012,/stage-1/result/result,None
2,3,3,4.0,+0:06,0,HUTAROVICH Yauheni,28,FDJ - BigMat,2.0,18.0,...,RR,Prospect,Clare,0,1,149 km,ME - Men Elite,race/tour-down-under/2012,/stage-1/result/result,None
3,4,4,8.0,+0:10,0,SABATINI Fabio,26,Liquigas - Cannondale,1.0,13.0,...,RR,Prospect,Clare,0,1,149 km,ME - Men Elite,race/tour-down-under/2012,/stage-1/result/result,13ed0fc8c2b0dcd2c4e1ac48b88166b8
4,5,5,9.0,+0:10,0,BENNATI Daniele,31,RadioShack - Nissan,1.0,10.0,...,RR,Prospect,Clare,0,1,149 km,ME - Men Elite,race/tour-down-under/2012,/stage-1/result/result,c0c77a7b1a8b55d9641962ba21981cab

In [62]:
race.columns

Index(['id', 'Rnk', 'GC', 'Timelag', 'BiB', 'Rider', 'Age', 'Team', 'UCI',
       'Pnt', 'Time', 'Circuit', 'Race_Name', 'Stage_Name', 'Date',
       'Stage_Type', 'Start', 'Finish', 'Race_ID', 'Stage_Number', 'Length',
       'Category', 'Race_url', 'Stage_url', 'rider_id'],
      dtype='object')

In [ ]:
race.drop([''])